language: ruby
cache: bundler
sudo: false
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails42.gemfile
services:
  - memcached
branches:
  only: [master]
before_install: gem install bundler
